In [2]:
from tensorflow.keras.layers import Dense, SimpleRNN
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

In [ ]:
phrase = "Good Morning"
characters = list(set(phrase.lower()))

In [4]:
characters

['m', 'i', ' ', 'g', 'r', 'o', 'n', 'd']

In [5]:
dict1 = {}
dict2 = {}
for letter in range(len(characters)):
    dict1[characters[letter]] = letter
    dict2[letter] = characters[letter]

In [6]:
print(dict1)
print(dict2)

{'m': 0, 'i': 1, ' ': 2, 'g': 3, 'r': 4, 'o': 5, 'n': 6, 'd': 7}
{0: 'm', 1: 'i', 2: ' ', 3: 'g', 4: 'r', 5: 'o', 6: 'n', 7: 'd'}


In [37]:
def convert_phrase(phraseP):
    list = []
    for letter in phraseP:
        if letter != "0":
            list.append(dict1[letter.lower()])
    return list


converted_phrase = convert_phrase(phrase)
print(converted_phrase)

[3, 5, 5, 7, 2, 0, 5, 4, 6, 1, 6, 3]


In [8]:
sequence_length = 4

In [9]:
(len(converted_phrase)-sequence_length)+1

9

In [10]:
sequence_length = 4
features = []
target = []
for i in range(0, (len(converted_phrase)-sequence_length)):
    slice = converted_phrase[i:i+sequence_length]
    features.append(slice)
    target.append(converted_phrase[i+sequence_length])
print(features)
print(target)

[[3, 5, 5, 7], [5, 5, 7, 2], [5, 7, 2, 0], [7, 2, 0, 5], [2, 0, 5, 4], [0, 5, 4, 6], [5, 4, 6, 1], [4, 6, 1, 6]]
[2, 0, 5, 4, 6, 1, 6, 3]


In [11]:
baseArray = np.zeros((8, 4, 8))
baseArray[0]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
#baseArray[0][0][5] = 1
#print(baseArray)

In [13]:
for b in range(len(baseArray)):
    for r in range(len(baseArray[b])):
        c = features[b][r]
        baseArray[b][r][c] = 1
print(baseArray)


[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]]]


In [18]:
sequentialRNN = Sequential([
    SimpleRNN(128, input_shape = (sequence_length, len(characters))),
    Dense(len(characters), activation='sigmoid')
])


c:\Users\kaige\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
sequentialRNN.compile(optimizer = "adam", metrics = ["accuracy"], loss = "sparse_categorical_crossentropy")

In [26]:
expTarget = np.expand_dims(target, axis = (1))

In [27]:
sequentialRNN.fit(baseArray, expTarget, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2500 - loss: 2.0190
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 1.8500
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6250 - loss: 1.6874
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 1.5314
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 1.3825
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 1.2409
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 1.1073
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.9819
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.8652
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.7577
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.6595
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.5707
Epo

In [22]:
print(type(baseArray))

<class 'numpy.ndarray'>


In [41]:
valueToPredict = "morn"

if len(valueToPredict) < 4:
    formatted_input = valueToPredict.zfill(4)
else:
    formatted_input = valueToPredict[-sequence_length:len(valueToPredict)]

converted_phrase1= convert_phrase(formatted_input)
print(formatted_input)
print(converted_phrase1)


morn
[0, 5, 4, 6]


In [47]:
baseArray = np.zeros((1, 4, 8))
print(baseArray)
print(len(baseArray[0]))

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]
4


In [48]:
baseArray = np.zeros((1, 4, 8))

for r in range(len(baseArray[0])):
    item = converted_phrase1[r]
    baseArray[0][r][item] = 1
print(baseArray)

[[[1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]]]


In [52]:
prediction = dict2[np.argmax(sequentialRNN.predict(baseArray))]
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
i
