In [1]:
from tensorflow.keras.layers import Dense, SimpleRNN
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

In [2]:
words = ""
phrase = "Good Morning how is your morning"
clean_phrase = phrase.lower()
words = clean_phrase.split(" ")

In [26]:
print(words)

['good', 'morning', 'how', 'is', 'your', 'morning']


In [3]:
words_set = set(words)
words_set = list(words_set)
dict1 = {}
dict2 = {}
for word in range(len(words_set)):
    dict1[words_set[word]] = word
    dict2[word] = words_set[word]

In [4]:
print(f"{dict1}\n{dict2}")

{'good': 0, 'your': 1, 'morning': 2, 'is': 3, 'how': 4}
{0: 'good', 1: 'your', 2: 'morning', 3: 'is', 4: 'how'}


In [5]:
def convert_phrase(phraseP):
    list = []
    for word in phraseP:
        if word != "0":
            list.append(dict1[word.lower()])
    return list


converted_phrase = convert_phrase(words)
print(converted_phrase)

[0, 2, 4, 3, 1, 2]


In [6]:
sequence_length = 1
features = []
target = []
for i in range(0, (len(converted_phrase)-sequence_length)):
    slice = converted_phrase[i:i+sequence_length]
    features.append(slice)
    target.append(converted_phrase[i+sequence_length])
print(features)
print(target)

[[0], [2], [4], [3], [1]]
[2, 4, 3, 1, 2]


In [7]:
baseArray = np.zeros(((len(converted_phrase)-sequence_length), 1, len(converted_phrase)))
baseArray

array([[[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]]])

In [8]:
for w in range(len(baseArray)):
    c = features[w][0]
    baseArray[w][0][c] = 1
print(baseArray)

[[[1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]]]


In [9]:
sequentialRNNwords = Sequential([
    SimpleRNN(128, input_shape = (sequence_length, len(words))),
    Dense(len(words), activation='sigmoid')
])

c:\Users\kaige\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
sequentialRNNwords.compile(optimizer = "adam", metrics = ["accuracy"], loss = "sparse_categorical_crossentropy")

In [11]:
expTarget = np.expand_dims(target, axis = (1))

In [12]:
sequentialRNNwords.fit(baseArray, expTarget, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 1.7997
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.2000 - loss: 1.7700
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.2000 - loss: 1.7406
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2000 - loss: 1.7115
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4000 - loss: 1.6825
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4000 - loss: 1.6538
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 1.6254
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 1.5972
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 1.5693
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 1.5417
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8000 - loss: 1.5142
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8000 - loss: 1.4871

In [25]:
valueToPredict = "good morning how is your"
valueToPredict = valueToPredict.lower()
new_words = valueToPredict.split(" ")



converted_phrase1= convert_phrase(new_words)
#converted_phrase1 = converted_phrase1[-1]
print(converted_phrase1)

[0, 2, 4, 3, 1]


In [26]:
baseArray = np.zeros((len(converted_phrase1), 1, len(converted_phrase)))
#baseArray = np.zeros((1, 1, len(converted_phrase)))
baseArray

array([[[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]]])

In [27]:
print(type(baseArray))
print(baseArray[-1])

<class 'numpy.ndarray'>
[[0. 0. 0. 0. 0. 0.]]


In [28]:
for w in range(len(baseArray)):
    c = converted_phrase1[w]
    baseArray[w][0][c] = 1
print(baseArray)

[[[1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]]]


In [127]:
print(baseArray[-1])

[[0. 1. 0. 0. 0. 0.]]


In [29]:
expArray = np.expand_dims(baseArray[-1], axis = (1))
expArray

array([[[0., 1., 0., 0., 0., 0.]]])

In [30]:
prediction = dict2[np.argmax(sequentialRNNwords.predict(expArray))]
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
morning


In [33]:
valueToPredict = "good morning how is your morning"
valueToPredict = valueToPredict.lower()
new_words = valueToPredict.split(" ")

converted_phrase1= convert_phrase(new_words)
print(converted_phrase1)

baseArray = np.zeros((len(converted_phrase1), 1, len(converted_phrase)))


for w in range(len(baseArray)):
    c = converted_phrase1[w]
    baseArray[w][0][c] = 1
print(baseArray)

expArray = np.expand_dims(baseArray[-1], axis = (1))
expArray

prediction = dict2[np.argmax(sequentialRNNwords.predict(expArray))]
print(prediction)

[0, 2, 4, 3, 1, 2]
[[[1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
how
