In [10]:
from tensorflow.keras.layers import Dense, SimpleRNN
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

In [25]:
words = ""
phrase = "Good Morning how is your morning"
clean_phrase = phrase.lower()
words = clean_phrase.split(" ")

In [26]:
print(words)

['good', 'morning', 'how', 'is', 'your', 'morning']


In [28]:
words_set = set(words)
words_set = list(words_set)
dict1 = {}
dict2 = {}
for word in range(len(words_set)):
    dict1[words_set[word]] = word
    dict2[word] = words_set[word]

In [29]:
print(f"{dict1}\n{dict2}")

{'your': 0, 'morning': 1, 'how': 2, 'is': 3, 'good': 4}
{0: 'your', 1: 'morning', 2: 'how', 3: 'is', 4: 'good'}


In [ ]:
def convert_phrase(phraseP):
    list = []
    for word in phraseP:
        if word != "0":
            list.append(dict1[word.lower()])
    return list


converted_phrase = convert_phrase(words)
print(converted_phrase)

[4, 1, 2, 3, 0, 1]


In [31]:
sequence_length = 1
features = []
target = []
for i in range(0, (len(converted_phrase)-sequence_length)):
    slice = converted_phrase[i:i+sequence_length]
    features.append(slice)
    target.append(converted_phrase[i+sequence_length])
print(features)
print(target)

[[4], [1], [2], [3], [0]]
[1, 2, 3, 0, 1]


In [36]:
baseArray = np.zeros(((len(converted_phrase)-sequence_length), 1, len(converted_phrase)))
baseArray

array([[[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]]])

In [38]:
for w in range(len(baseArray)):
    c = features[w][0]
    baseArray[w][0][c] = 1
print(baseArray)

[[[0. 0. 0. 0. 1. 0.]]

 [[0. 1. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0. 0.]]]


In [39]:
sequentialRNNwords = Sequential([
    SimpleRNN(128, input_shape = (sequence_length, len(words))),
    Dense(len(words), activation='sigmoid')
])

c:\Users\kaige\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [40]:
sequentialRNNwords.compile(optimizer = "adam", metrics = ["accuracy"], loss = "sparse_categorical_crossentropy")

In [41]:
expTarget = np.expand_dims(target, axis = (1))

In [42]:
sequentialRNNwords.fit(baseArray, expTarget, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0000e+00 - loss: 1.8701
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.0000e+00 - loss: 1.8412
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 1.8126
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.0000e+00 - loss: 1.7842
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.0000e+00 - loss: 1.7560
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0000e+00 - loss: 1.7281
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0000e+00 - loss: 1.7004
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 1.6729
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0000e+00 - loss: 1.6457
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4000 - loss: 1.6187
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6000 - loss: 1.5919
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step -

In [68]:
valueToPredict = "good morning"
valueToPredict = valueToPredict.lower()
new_words = valueToPredict.split(" ")

converted_phrase1= convert_phrase(new_words)
print(converted_phrase1)

[4, 1]


In [72]:
baseArray = np.zeros(((len(converted_phrase1)-sequence_length), 1, len(converted_phrase)))
baseArray

array([[[0., 0., 0., 0., 0., 0.]]])

In [54]:
print(type(baseArray))
print(baseArray[0][0][0])

<class 'numpy.ndarray'>
0.0


In [ ]:
for w in range(len(baseArray[0])):
    item = converted_phrase1[w]
    baseArray[0][w][item] = 1
print(baseArray)

3
[[[0. 0. 0. 1. 0. 0.]]]


In [59]:
prediction = dict2[np.argmax(sequentialRNNwords.predict(baseArray))]
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
your


In [ ]:
valueToPredict = "good morning"
valueToPredict = valueToPredict.lower()
new_words = valueToPredict.split(" ")

converted_phrase1= convert_phrase(new_words)
print(converted_phrase1)

baseArray = np.zeros((1, 1, len(converted_phrase)))


for w in range(len(baseArray[0])):
    item = converted_phrase1[w]
    baseArray[0][w][item] = 1
print(baseArray)

prediction = dict2[np.argmax(sequentialRNNwords.predict(baseArray))]
print(prediction)

KeyError: 'good morning'